### PR TITLE
reading multiple registers at once

### PR DESCRIPTION
**Pull request by geronet1**
I wanted to request multiple values from the SDM630 to save time to get a reading interval of 1 second. It works perfect.
Reading 20 registers in 100 ms with a RESPONSE_TIMEOUT of 1 is no problem.

### CODE REVIEW

**Comment by reaper7** [comment]
I don't have the physical possibility to check the functioning of the code but I would be happy to include your work.
so...
has everything been checked by you? examples compile and basic configuration works?

**Comment by Adminius** [comment]
@reaper7 are you planing to do a new release with this feature?

**Comment by reaper7** [comment]
@Adminius - I have no way to check it, the only way is through feedback. Have you checked this feature?

Besides, I need to add comments to the readme...

**Comment by reaper7** [comment]
some comments, not about multiple reading ;)

**Comment by Adminius** [comment]
@reaper7 https://github.com/reaper7/SDM_Energy_Meter/pull/85
tested ;)

**Pull request merged**
