### PR TITLE
Added registers for DDM18SD

### PR DESCRIPTION
**Pull request by jeroenst**

### CODE REVIEW

**Comment by reaper7** [comment]
Hi!
Have you tested this device? it works?

**Comment by jeroenst** [comment]
Not yet, I did integrate the registers from the documentation. I will receive the device 15-5-2020 and will install and test it the same day.

To be continued...

**Comment by reaper7** [comment]
Ok, then we'll wait for physical tests...
if everything goes well we will add Your integration.

Let me know when you check.

**Comment by jeroenst** [comment]
Sorry, I don't think I will use this device soon, for now I use a zmai90. So at this moment I won't test this code.

**Comment by Jestergnet** [comment]
Doesn't work, reading errors hiss. Where to dig?

SDM READ ERR. COUNT | 225 | total
SDM READ ERR. CODE |  4 | code

**Comment by Jestergnet** [comment]
I checked it works.

**Comment by jeroenst** [comment]
Please merge now or has been tested.

**Comment by reaper7** [comment]
Please update your copy of this repo because structure of SDM.h and nomenclature of registry names has been changed.
You must create definitions for the new device according to the example from SDM.h (example from lines 194-202)

**Comment by reaper7** [comment]
done!

**Comment by digimp** [comment]
Looking for see this device (DDM18SD) working found your contribution here. On the code of the tasmota sensor there isn't , or I have'nt found, nothing for this device. So finally this is the reason why it doesn't work in my hands. Do I have to add this register on a override file or I have to start to compile a full file from the beginning to the end ?

**Comment by reaper7** [comment]
I don't use tasmota and I don't know how it's built...
You can try of course ...

**Comment by digimp** [comment]
Ah, thanks for quick answer! I'll try to do what I can, not easy. Thanks for your work, I'll have anyway the chance to read my meter.

**Pull request closed without merging**
