### PR TITLE
Sdm72

### PR DESCRIPTION
**Pull request by jegaha**
Hey reaper7, 
thank you for your great work. It was a great pleasure for me to take and extend your library to use my SDM72 Energy Meter.
Register description was taken from this source https://bg-etech.de/download/manual/SDM72D-M-DE.pdf
Regards,
 jegaha

### CODE REVIEW

**Comment by reaper7** [comment]
as I understand you tested this? :D

**Comment by jegaha** [comment]
Yes, I managed to make it run. My only Problem with the combination of D1 mini/RS485/SDM_72 was that it only runs in HW serial mode. My first test setup with Arduino/RS485/SDM_72 runs in both HW and SW serial mode. Maybe a timing problem or a weak timing source on the D1 mini.

Bildschirmfoto 2019-09-10 um 14 37 15

**Comment by jegaha** [comment]
The hardware is now mounted on a 3D-printed carrier and is counting and monitoring the energyconsumption of the EVCS.
DSC_2001_snippet

**Comment by TomaszSz7** [comment]
Hey
I have an issue with the implementation of SDM72D-M reading in TASMOTA. Anyone can help with this?
any suggestions?  Maybe someone's already have compile tasmota bin and can share ?  
i will appreciate it :-) 
Br
Tomasz

**Pull request merged**
